/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fts.panels;

import dialogs.ApplicationLogDialog;
import dialogs.ApproveRejectDialog;
import fts.frames.Login;
import fts.utils.ConnectToMYSQL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rafi0
 */
public class ApplicationsReport extends javax.swing.JPanel {
    public static String loadoption;
    public ConnectToMYSQL con=null;
    /**
     * Creates new form ApproveRejectApplications
     */
    public ApplicationsReport() {
        initComponents();

        con=new ConnectToMYSQL();
        LoadApplicationsByStatus();
    }
    private void LoadApplicationsByStatus(){
        
         try{
             ResultSet rs=null;
            rs=con.getResultSet("select app_id as `Application No`,app_title `App. Title`,GetDateText(app_date) as `Submitted On`,GetDomainValue(status) as `Status`,GetUserAlias(submitted_by) as `Applicant`,GetUserAlias(cur_user) as `Current User`,GetUserAlias(approved_by) as `Approver` from applications ");
             
            jtbl.setModel(con.buildTableModel(rs));
      }catch(Exception ex){
          
             System.err.println(ex+"");
      }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("All Applications");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblMouseClicked
        // TODO add your handling code here:
           JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            String val=source.getModel().getValueAt(row, 0)+"";
            int appno=Integer.parseInt(val);
            new ApplicationLogDialog(appno).setVisible(true);
                    
         

    }//GEN-LAST:event_jtblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl;
    // End of variables declaration//GEN-END:variables
}
