/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fts.panels;

import dialogs.ApplicationLogDialog;
import dialogs.ApproveRejectDialog;
import fts.frames.Login;
import fts.utils.ConnectToMYSQL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rafi0
 */
public class OfficerMapping extends javax.swing.JPanel {
    public static String loadoption;
    public ConnectToMYSQL con=null;
    /**
     * Creates new form ApproveRejectApplications
     */
    public OfficerMapping() {
        initComponents();

        con=new ConnectToMYSQL();
        InitUI();
        LoadDeptDocTable();
    }
    private void InitUI(){
          
         try{
            ResultSet rs=con.getResultSet("select dept_name from departments");
            cmb_dept.removeAllItems();
            while(rs.next()){
                cmb_dept.addItem(rs.getString("dept_name"));
            }
        }catch(Exception ex){
            
        }
          try{
            ResultSet rs=con.getResultSet("select user_name from users where user_type=1");
            cmb_officer.removeAllItems();
            while(rs.next()){
                cmb_officer.addItem(rs.getString("user_name"));
            }
        }catch(Exception ex){
            
        }
        try{
            ResultSet rs=con.getResultSet("select type_name from app_types_master");
            cmb_document.removeAllItems();
            while(rs.next()){
                cmb_document.addItem(rs.getString("type_name"));
            }
        }catch(Exception ex){
            
        }
    }
    private void LoadDeptDocTable(){
        
         try{
             ResultSet rs=null;
            rs=con.getResultSet("select a.type_name as `Application`,b.dept_name as `Department`,GetUserAlias(dept_mgr) as `Manager` from app_types_master a left join departments b on a.dept_id=b.dept_id");
             
            jtbl.setModel(con.buildTableModel(rs));
      }catch(Exception ex){
          
             System.err.println(ex+"");
      }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmb_dept = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmb_officer = new javax.swing.JComboBox<>();
        btn_saveofficer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmb_document = new javax.swing.JComboBox<>();
        btn_savedoc = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Department");

        cmb_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Officer");

        cmb_officer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_saveofficer.setText("Save");
        btn_saveofficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveofficerActionPerformed(evt);
            }
        });

        jLabel3.setText("Document");

        cmb_document.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_savedoc.setText("Save");
        btn_savedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_savedocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_document, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(btn_savedoc)
                            .addComponent(btn_saveofficer))
                        .addGap(0, 193, Short.MAX_VALUE))
                    .addComponent(cmb_officer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_officer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_saveofficer)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_document, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_savedoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Officer - Application Mapping");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblMouseClicked
        // TODO add your handling code here:
           JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            String val=source.getModel().getValueAt(row, 0)+"";
            int appno=Integer.parseInt(val);
            new ApplicationLogDialog(appno).setVisible(true);
                    
         

    }//GEN-LAST:event_jtblMouseClicked

    private void btn_saveofficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveofficerActionPerformed
        // TODO add your handling code here:
        String dept_mgr=con.getSingleStringVal("select uid from users where user_name='"+cmb_officer.getSelectedItem()+"'");
        String sql="update departments set dept_mgr="+dept_mgr+" where dept_name='"+cmb_dept.getSelectedItem()+"'";
        if(con.ExecuteQuery(sql)>0){
            JOptionPane.showMessageDialog(this, "Successfuilly Updated");
        }
        LoadDeptDocTable();
    }//GEN-LAST:event_btn_saveofficerActionPerformed

    private void btn_savedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_savedocActionPerformed
        // TODO add your handling code here:
        String dept_id=con.getSingleStringVal("select dept_id from departments where dept_name='"+cmb_dept.getSelectedItem()+"'");
        String sql="update app_types_master set dept_id="+dept_id+" where type_name='"+cmb_document.getSelectedItem()+"'";
        if(con.ExecuteQuery(sql)>0){
            JOptionPane.showMessageDialog(this, "Successfuilly Updated");
        }
          LoadDeptDocTable();
    }//GEN-LAST:event_btn_savedocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_savedoc;
    private javax.swing.JButton btn_saveofficer;
    private javax.swing.JComboBox<String> cmb_dept;
    private javax.swing.JComboBox<String> cmb_document;
    private javax.swing.JComboBox<String> cmb_officer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtbl;
    // End of variables declaration//GEN-END:variables
}
