/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fts.panels;

import static dialogs.ApproveRejectDialog.app_no;
import fts.frames.Login;
import fts.utils.ConnectToMYSQL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafi0
 */
public class TrackAppStatus extends javax.swing.JPanel {

    /**
     * Creates new form NewApplicationForm
     */
    ConnectToMYSQL con;
    public TrackAppStatus() {
        con=new ConnectToMYSQL();
        initComponents();
       btn_submit.setEnabled(false);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txt_submitted_date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_approver = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_curuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_appno = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        txt_subject = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_remarks = new javax.swing.JTextField();
        txt_doctype = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Track Status");

        jLabel3.setText("Submitted On");

        txt_status.setEditable(false);

        jLabel7.setText("Document");

        jLabel2.setText("Description:");

        btn_submit.setText("Cancel Application");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        txt_desc.setEditable(false);
        txt_desc.setColumns(20);
        txt_desc.setRows(5);
        jScrollPane1.setViewportView(txt_desc);

        jLabel4.setText("Status");

        txt_submitted_date.setEditable(false);

        jLabel5.setText("Approved/Rejected  By");

        txt_approver.setEditable(false);

        jLabel6.setText("Current User");

        txt_curuser.setEditable(false);

        jLabel8.setText("App. No");

        btn_search.setText("Seach");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        txt_subject.setEditable(false);

        jLabel9.setText("Subject:");

        jLabel11.setText("Remarks");

        txt_remarks.setEditable(false);
        txt_remarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remarksActionPerformed(evt);
            }
        });

        txt_doctype.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btn_submit))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(txt_status)
                            .addComponent(txt_curuser)
                            .addComponent(txt_submitted_date)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_appno, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_search))
                            .addComponent(txt_approver, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_remarks)
                            .addComponent(txt_doctype, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_appno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_submitted_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_doctype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_approver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_curuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btn_submit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
       int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you want to cancel application?", "Conform", dialogButton);
        if(dialogResult == 0) {
                String sql="delete from applications where app_id="+txt_appno.getText();
                if(con.ExecuteQuery(sql)>0){
                      JOptionPane.showMessageDialog(this,"Application Cancelled Successfully");
                }else{
                      JOptionPane.showMessageDialog(this,"Unable to delete");
                }
            
        } 

            //submitting to databse
           // int app_type=con.getSingleIntVal("select type_id from app_types_master where type_name='"+cmb_document.getSelectedItem().toString()+"'");
            //int curuser=con.getSingleIntVal("select dept_mgr from departments where dept_id in (select dept_id from app_types_master where type_name='"+cmb_document.getSelectedItem().toString()+"')");
           // if(curuser<=0){
             //   JOptionPane.showMessageDialog(this,"No Officer Assigned for this document.");
               // return;
           // }//
           // String sql="insert into applications (app_title,app_desc,submitted_by,status,cur_user,app_type) values ('"+txt_status.getText()+"','"+txt_desc.getText()+"',"+Login._uid+",1,"+curuser+","+app_type+")";
         ///  long retval=con.InsertQuery(sql);
          //  if(retval>0){
                //  JOptionPane.showMessageDialog(this,"Application Submitted Successfully.\nYour Application No is :"+retval);
                
            
      //  }
       // else{
      //      JOptionPane.showMessageDialog(null, "Accept the terms to submit the application");
       // }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        btn_submit.setEnabled(false);
        LoadAppDetails();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_remarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_remarksActionPerformed
 private void LoadAppDetails(){
         btn_submit.setEnabled(false);
        ResultSet rs=con.getResultSet("select app_title,status sval,app_desc,GetDateText(app_date) as app_date,GetUserAlias(submitted_by) submitted_by,GetUserAlias(approved_by) approved_by,GetUserAlias(cur_user) current,GetDomainValue(status) as status,GetTypeName(app_type) as app_type from applications where app_id="+txt_appno.getText()+"");
        try{
        if(rs.next()){
            txt_subject.setText(rs.getString("app_title"));
            txt_desc.setText(rs.getString("app_desc"));
            if(rs.getInt("sval")==1){
                 btn_submit.setEnabled(true);
            }
            txt_submitted_date.setText(rs.getString("app_date"));
            txt_status.setText(rs.getString("status"));
            txt_doctype.setText(rs.getString("app_type")); 
            txt_approver.setText(rs.getString("approved_by")); 
            txt_curuser.setText(rs.getString("current")); 
            txt_remarks.setText(con.getSingleStringVal("select remarks from status_tracking where app_id="+txt_appno.getText()+" order by track_id desc limit 1")); 


        }else{
             JOptionPane.showMessageDialog(this,"Invalid Application No.");
        }
        }catch(Exception ex){
                       JOptionPane.showMessageDialog(this,"Error");  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_appno;
    private javax.swing.JTextField txt_approver;
    private javax.swing.JTextField txt_curuser;
    private javax.swing.JTextArea txt_desc;
    private javax.swing.JTextField txt_doctype;
    private javax.swing.JTextField txt_remarks;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_subject;
    private javax.swing.JTextField txt_submitted_date;
    // End of variables declaration//GEN-END:variables
}
